wso2/docker-apim

docker-compose/pattern-1/api-manager/carbon/repository/conf/api-manager.xml
Swagger UI try to send the request to local IP of docker container. This fails because it's not accessible from the host.
=> Changing API Gateway URL to localhost. If we don't set this explicitly Swagger UI fails when trying out an API

dockerfiles/apim-analytics/README.md, dockerfiles/apim/README.md
> This pull request fixes a formatting issue caused by incorrect README.md file syntax used to define links.
> Correct the README.md file syntax to define links, to fix the formatting issue.
> Add correct README.md file syntax to define links, to fix the formatting issue.
=> Fix formatting issue in links within README.md files

README.md, dockerfiles/apim-analytics/README.md, dockerfiles/apim/README.md
> Need to refine the standalone WSO2 API Manager Dockerfile README.md file. Related issue is https://github.com/wso2/docker-apim/issues/61.
> Refine the standalone WSO2 API Manager Dockerfile README.md file.
=> Refine the standalone WSO2 API Manager Dockerfile README.md

docker-compose/apim-analytics/README.md, docker-compose/apim-analytics/am-analytics/carbon/repository/conf/datasources/analytics-datasources.xml, docker-compose/apim-analytics/am-analytics/carbon/repository/conf/datasources/stats-datasources.xml, docker-compose/apim-analytics/api-manager/carbon/repository/conf/datasources/master-datasources.xml, docker-compose/apim-analytics/docker-compose.yml
The username in the Dockerfiles has been updated to `wso2carbon`. Hence the target file path in `docker-compose.yml` file has to be updated. Also, update the mysql jdbc driver.
Fix file path inconsistency in docker-compose.yml and update the mysql jdbc driver. 
- Update the target file path in docker-compose.yml 
- Update the mysql jdbc driver version to v5.1.45 due to security vulnerabilities in older versions 
- Disable SSL in jdbc connection using property `&amp;useSSL=false` to avoid warnings printed when db operations are performed
The reason to disable SSL is the mysql container generate SSL certs when the container starts up via a [docker-entrypoint.sh](https://github.com/docker-library/mysql/blob/master/5.7/docker-entrypoint.sh#L94) script. Since the docker compose configs are …
=> Fix user home dir and update mysql jdbc driver

dockerfiles/apim-analytics/Dockerfile, dockerfiles/apim/Dockerfile, dockerfiles/is-as-km/Dockerfile
In order to manage permissions of volumes mounted to the Docker container, it is required to specify the user id and group id explicitly. Hence specify the user id and group id in the Dockerfile. Fix #81.
=> Set user id and group id of user executing the server script 

.gitignore
> The `dockerfiles/apim/files` and  `dockerfiles/is-as-km/files` folders are missing. These need to be added to 2.5.x branch.
> Add files folder required for Docker image builds.
=> Add files folder required for Docker image builds

CHANGELOG.md, README.md, docker-compose/apim-is-as-km-with-analytics/README.md, docker-compose/apim-is-as-km-with-analytics/docker-compose.yml, docker-compose/apim-is-as-km-with-analytics/scripts/README.md, docker-compose/apim-is-as-km-with-analytics/scripts/deploy.sh, docker-compose/apim-with-analytics/docker-compose.yml, docker-compose/apim-with-analytics/scripts/README.md, docker-compose/apim-with-analytics/scripts/deploy.sh, dockerfiles/alpine/apim-analytics/base/Dockerfile, dockerfiles/alpine/apim/Dockerfile, dockerfiles/alpine/is-as-km/Dockerfile, dockerfiles/ubuntu/apim-analytics/base/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile, dockerfiles/ubuntu/is-as-km/Dockerfile
> Integrate support in Docker Compose resources for usage of both types of users: users with and without WSO2 subscriptions. Currently, only users with WSO2 subscriptions can utilize Docker Compose resources. This fixes https://github.com/wso2/docker-apim/issues/197. This PR also upgrades the AdoptOpenJDK version used in Docker resources with the latest version - `jdk8u212-b03`. Hence, it fixes https://github.com/wso2/docker-apim/issues/196.
> Integrate support in Docker Compose resources for users with and without WSO2 subscriptions
=> Integrate support in Docker Compose resources for users with and without WSO2 subscriptions

README.md, dockerfiles/alpine/apim/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
> Install libxml2-utils package required by API Manager profile startup script in Alpine and Ubuntu based Docker resources. This fixes https://github.com/wso2/docker-apim/issues/183.
> Install libxml2-utils package in Alpine and Ubuntu based Docker resources
=> Install libxml2-utils package in Alpine and Ubuntu based Docker resources

dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/alpine/apim/Dockerfile, dockerfiles/alpine/is-as-km/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/centos/is-as-km/Dockerfile, dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile, dockerfiles/ubuntu/is-as-km/Dockerfile
> Use WSO2 product pack downloadable links to binaries available at JFrog Bintray. This fixes https://github.com/wso2/docker-apim/issues/224.
> Use WSO2 product pack downloadable links to binaries available at JFrog Bintray
=> Use WSO2 product pack downloadable links to binaries available at JFrog Bintray

dockerfiles/alpine/is-as-km/Dockerfile, dockerfiles/centos/is-as-km/Dockerfile, dockerfiles/ubuntu/is-as-km/Dockerfile
> Add artifacts required for WSO2 Kubernetes membership scheme to IS as KM Docker resources. This fixes https://github.com/wso2/docker-apim/issues/227.
> Package the Kubernetes Membership Scheme in WSO2 Identity Server as KM Docker images
=> Add artifacts required for WSO2 Kubernetes membership scheme to IS as KM Docker resources

CHANGELOG.md, README.md, dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/alpine/apim/Dockerfile, dockerfiles/alpine/is-as-km/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/centos/is-as-km/Dockerfile, dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile, dockerfiles/ubuntu/is-as-km/Dockerfile
> Upgrade AdoptOpenJDK version to the latest version - jdk8u222-b10. This fixes https://github.com/wso2/docker-apim/issues/235.
> Upgrade AdoptOpenJDK version to the latest version
=> Upgrade AdoptOpenJDK version to the latest version - jdk8u222-b10

.metadata, CHANGELOG.md, CONTRIBUTING.md, README.md, dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/dashboard/README.md, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/alpine/apim-analytics/worker/README.md, dockerfiles/alpine/apim/Dockerfile, dockerfiles/alpine/apim/README.md, dockerfiles/alpine/is-as-km/Dockerfile, dockerfiles/alpine/is-as-km/README.md, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/README.md, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim-analytics/worker/README.md, dockerfiles/centos/apim/Dockerfile, dockerfiles/centos/apim/README.md, dockerfiles/centos/is-as-km/Dockerfile, dockerfiles/centos/is-as-km/README.md, dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/dashboard/README.md, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/README.md, dockerfiles/ubuntu/apim/Dockerfile, dockerfiles/ubuntu/apim/README.md, dockerfiles/ubuntu/is-as-km/Dockerfile, dockerfiles/ubuntu/is-as-km/README.md
> Create Docker resources for WSO2 API Management profiles v3.0.0. Also, this introduces the metadata file required by the infrastructure resource generator. This fixes https://github.com/wso2/docker-apim/issues/241 and fixes https://github.com/wso2/docker-apim/issues/243.
> Create Docker resources for WSO2 API Management profiles v3.0.0
=> Create Docker resources for WSO2 API Management profiles v3.0.0

dockerfiles/alpine/apim-analytics/dashboard/README.md, dockerfiles/centos/apim-analytics/dashboard/README.md, dockerfiles/ubuntu/apim-analytics/dashboard/README.md
- New version of analytics dashboard uses the context `/analytics-dashboard` instead of `/portal`. Rename context /portal to /analytics-dashboard
=> Rename context portal to analytics-dashboard

CHANGELOG.md, CONTRIBUTING.md, README.md, docker-compose/apim-is-as-km-with-analytics/README.md, docker-compose/apim-is-as-km-with-analytics/scripts/README.md, docker-compose/apim-with-analytics/README.md, docker-compose/apim-with-analytics/scripts/README.md, dockerfiles/alpine/apim/Dockerfile, dockerfiles/alpine/apim/docker-entrypoint.sh, dockerfiles/centos/apim/docker-entrypoint.sh, dockerfiles/ubuntu/apim/docker-entrypoint.sh
> It has been discovered that the WSO2 API Manager version 2.6.x Docker images fail to accept product startup options. This PR fixes the original issue https://github.com/wso2/docker-apim/issues/250.
> Fix failure to accept product startup options
=> [API-Manager v2.6.x] Failure to accept product startup options

CHANGELOG.md, README.md, dockerfiles/alpine/apim/Dockerfile, dockerfiles/alpine/apim/docker-entrypoint.sh, dockerfiles/centos/apim/docker-entrypoint.sh, dockerfiles/ubuntu/apim/docker-entrypoint.sh
> It has been discovered that the WSO2 API Manager version 3.0.x Docker images fail to accept product startup options. This PR fixes https://github.com/wso2/docker-apim/issues/252.
> Fix failure to accept product startup options
=> [API-Manager v3.0.x] Failure to accept product startup options

CHANGELOG.md, dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/alpine/apim/Dockerfile, dockerfiles/alpine/is-as-km/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/centos/is-as-km/Dockerfile, dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile, dockerfiles/ubuntu/is-as-km/Dockerfile
> This PR upgrades the WSO2 API Management product profile Docker images to use AdoptOpenJDK 11. The used version is `jdk-11.0.6+10`. This fixes https://github.com/wso2/docker-apim/issues/288.
> Upgrade WSO2 API Management product profile Docker images to use AdoptOpenJDK 11
=> Upgrade WSO2 API Management product profile Docker images to use AdoptOpenJDK 11

dockerfiles/alpine/is-as-km/Dockerfile, dockerfiles/centos/is-as-km/Dockerfile, dockerfiles/ubuntu/is-as-km/Dockerfile
> This PR packages the latest version of Kubernetes Membership Scheme in WSO2 Identity Server as Key Manager Docker images. This fixes https://github.com/wso2/docker-apim/issues/286.
> Package the latest version of Kubernetes Membership Scheme in WSO2 Identity Server as Key Manager Docker images
=> Package the latest version of Kubernetes Membership Scheme in WSO2 Identity Server as Key Manager Docker images

CHANGELOG.md, dockerfiles/alpine/apim/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
> This PR removes the creation step of directory for persisting the local Carbon H2 database file. This closes https://github.com/wso2/docker-apim/issues/319.
> Avoid Creating Directory For Persisting Local Carbon H2 Database File
=> [3.2.0] Avoid Creating Directory For Persisting Local Carbon H2 Database File

CHANGELOG.md, dockerfiles/alpine/apim/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
> As per https://github.com/wso2/docker-apim/issues/319#issuecomment-661680037, this PR reverts the changes done under https://github.com/wso2/docker-apim/pull/320.
> Revert Avoiding Creation of Directory For Persisting Local Carbon H2 Database File
=> [3.2.0] Revert Avoiding Creation of Directory For Persisting Local Carbon H2 Database File

README.md, dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/alpine/apim/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
> This PR addresses $subject which is the new strategy followed in future product Docker image resources. This addresses https://github.com/wso2/docker-apim/issues/321.
> Avoid Packaging MySQL JDBC Driver in WSO2 Product Docker Images
=> [3.2.0] Avoid Packaging MySQL JDBC Driver in WSO2 Product Docker Images

CHANGELOG.md, dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/alpine/apim/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
> This PR addresses $subject, this fixes https://github.com/wso2/docker-apim/issues/336.
> Upgrade AdoptOpenJDK 11 version to the latest version - 11.0.8_10-jdk
=> [3.2.0] Upgrade AdoptOpenJDK 11 version to the latest version - 11.0.8_10-jdk

docker-compose/apim-is-as-km-with-analytics/README.md
> In the Docker Compose setup involving API Manager with Identity Server as Key Manager, it needs to be instructed to replace the packaged IS extensions with the latest as per official [documentation](https://apim.docs.wso2.com/en/next/administer/key-managers/configure-wso2is-connector/#step-1-configure-wso2-is). This PR adds the necessary instruction.
> Add Instruction to Replace IS Extensions
=> [3.2.0] Add Instruction to Replace IS Extensions

dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/alpine/apim/Dockerfile, dockerfiles/alpine/is-as-km/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/centos/is-as-km/Dockerfile, dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile, dockerfiles/ubuntu/is-as-km/Dockerfile
> This PR introduces the Docker source Git release tag as a label and enable SSL verification for `wget`. This fixes #347, #348. 
> Introduce the Docker source Git release tag as a label. 
Enable SSL verification for `wget`.
> Use the dockerfile instruction `LABEL` to add Git release tag as a label.
Removes existing option --no-check-certificate for wget.
>Client: Docker Engine - Community
Version:           19.03.12
API version:       1.40
Go version:        go1.13.10
Git commit:        48a66213fe
Built:             Mon Jun 22 15:45:36 2020
OS/Arch:           linux/amd64
Experimental:      false
>Server: Docker Engine - Community
Engine:
Version:          19.03.12
API version:      1.40 (minimum version 1.12)
Go version:       go1.13.10
Git commit:       48a66213fe
Built:            Mon …
=> [3.1.0] Add Git release tag as a label & enable SSL cert verification for wget 

dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/alpine/apim/Dockerfile, dockerfiles/alpine/is-as-km/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/centos/is-as-km/Dockerfile, dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile, dockerfiles/ubuntu/is-as-km/Dockerfile
> This PR introduces the Docker source Git release tag as a label and enable SSL verification for `wget`. This fixes #351, #350 . 
> Introduce the Docker source Git release tag as a label. 
Enable SSL verification for `wget`.
> Use the dockerfile instruction `LABEL` to add Git release tag as a label.
Removes existing option --no-check-certificate for wget.
>Client: Docker Engine - Community
Version:           19.03.12
API version:       1.40
Go version:        go1.13.10
Git commit:        48a66213fe
Built:             Mon Jun 22 15:45:36 2020
OS/Arch:           linux/amd64
Experimental:      false
>Server: Docker Engine - Community
Engine:
Version:          19.03.12
API version:      1.40 (minimum version 1.12)
Go version:       go1.13.10
Git commit:       48a66213fe
Built:            Mon …
=> [3.0.0] Add Git release tag as a label & enable SSL cert verification for wget

dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/alpine/apim/Dockerfile, dockerfiles/alpine/is-as-km/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/centos/is-as-km/Dockerfile, dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile, dockerfiles/ubuntu/is-as-km/Dockerfile
> This PR introduces the Docker source Git release tag as a label and enable SSL verification for `wget`. This fixes #353 #354. 
> Introduce the Docker source Git release tag as a label. 
Enable SSL verification for `wget`.
> Use the dockerfile instruction `LABEL` to add Git release tag as a label.
Removes existing option --no-check-certificate for wget.
>Client: Docker Engine - Community
Version:           19.03.12
API version:       1.40
Go version:        go1.13.10
Git commit:        48a66213fe
Built:             Mon Jun 22 15:45:36 2020
OS/Arch:           linux/amd64
Experimental:      false
>Server: Docker Engine - Community
Engine:
Version:          19.03.12
API version:      1.40 (minimum version 1.12)
Go version:       go1.13.10
Git commit:       48a66213fe
Built:            Mon …
=> [2.6.0] Add Git release tag as a label & enable SSL cert verification for wget

dockerfiles/alpine/apim-analytics/Dockerfile, dockerfiles/alpine/apim-analytics/README.md, dockerfiles/alpine/apim/Dockerfile, dockerfiles/alpine/apim/README.md, dockerfiles/alpine/is-as-km/Dockerfile, dockerfiles/alpine/is-as-km/README.md, dockerfiles/centos/apim-analytics/Dockerfile, dockerfiles/centos/apim-analytics/README.md, dockerfiles/centos/apim/Dockerfile, dockerfiles/centos/apim/README.md, dockerfiles/centos/is-as-km/Dockerfile, dockerfiles/centos/is-as-km/README.md, dockerfiles/ubuntu/apim-analytics/Dockerfile, dockerfiles/ubuntu/apim-analytics/README.md, dockerfiles/ubuntu/apim/Dockerfile, dockerfiles/ubuntu/apim/README.md, dockerfiles/ubuntu/is-as-km/Dockerfile, dockerfiles/ubuntu/is-as-km/README.md
> This PR introduces the Docker source Git release tag as a label and enable SSL verification for `wget`. This fixes #358, #359, #362   
> Introduce the Docker source Git release tag as a label. 
Enable SSL verification for `wget`.
> Use the dockerfile instruction `LABEL` to add Git release tag as a label.
Removes existing option --no-check-certificate for `wget` and update the CA certificates for `Ubuntu 16.04` by installing `ca-certificates` package.
>Client: Docker Engine - Community
Version:           19.03.12
API version:       1.40
Go version:        go1.13.10
Git commit:        48a66213fe
Built:             Mon Jun 22 15:45:36 2020
OS/Arch:           linux/amd64
Experimental:      false
>Server: Docker Engine - Community
Engine:
Version:          19.03.12
API version:      1.40 …
=> [2.5.0] Add Git release tag as a label & enable SSL cert verification for wget

CHANGELOG.md, README.md, dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/alpine/apim/Dockerfile, dockerfiles/alpine/is-as-km/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/centos/is-as-km/Dockerfile, dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile, dockerfiles/ubuntu/is-as-km/Dockerfile
Update base image due to vulnerability in package `libcrypto1.1`
fix https://github.com/wso2/docker-apim/issues/386
```
$ ./trivy --exit-code 0 --severity HIGH --no-progress alpine-apim:${COMMIT}
2020-12-01T01:10:29.927Z	INFO	Need to update DB
2020-12-01T01:10:29.927Z	INFO	Downloading DB...
2020-12-01T01:10:54.472Z	INFO	Detecting Alpine vulnerabilities...
2020-12-01T01:10:54.473Z	INFO	Trivy skips scanning programming language libraries because no supported file was detected
alpine-apim:f7896a80 (alpine 3.10.2)
====================================
Total: 2 (HIGH: 2)
+--------------+------------------+----------+-------------------+---------------+--------------------------------+
|   LIBRARY    | VULNERABILITY ID | SEVERITY | INSTALLED VERSION | FIXED VERSION |             TITLE …
```
=> [2.6.0] Upgrade AdoptOpenJDK version to the latest version - jdk8u272-b10

dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/alpine/apim/Dockerfile, dockerfiles/alpine/is-as-km/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/centos/is-as-km/Dockerfile, dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile, dockerfiles/ubuntu/is-as-km/Dockerfile
Update base image due to vulnerability in package `libcrypto1.1`, `libgcc`, `libssl1.1`, `libfreetype6`
fix #389
```
alpine-apim:5880aec2 (alpine 3.11.5)
====================================
Total: 3 (HIGH: 3)
+--------------+------------------+----------+-------------------+---------------+--------------------------------+
|   LIBRARY    | VULNERABILITY ID | SEVERITY | INSTALLED VERSION | FIXED VERSION |             TITLE              |
+--------------+------------------+----------+-------------------+---------------+--------------------------------+
| libcrypto1.1 | CVE-2020-1967    | HIGH     | 1.1.1d-r3         | 1.1.1g-r0     | openssl: Segmentation fault in |
|              |                  |          |                   |               | SSL_check_chain causes denial  |
| …
```
=> [3.1.0] Upgrade AdoptOpenJDK 11 version to the latest version - 11.0.9_11

dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/alpine/apim/Dockerfile, dockerfiles/alpine/is-as-km/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/centos/is-as-km/Dockerfile
Fix base image JDK version as jdk-11.0.9_11 in https://github.com/wso2/docker-apim/pull/390
```
alpine-apim:de1dd115 (alpine 3.12.1)
====================================
Total: 0 (HIGH: 0)
```
```
centos-apim:de1dd115 (centos 7.9.2009)
======================================
Total: 3 (HIGH: 3)
```
```
ubuntu-apim:de1dd115 (ubuntu 20.04)
===================================
Total: 0 (HIGH: 0)
```
=> [3.1.x] Fix base image JDK version as jdk-11.0.9_11

CHANGELOG.md, README.md, dockerfiles/centos/apim/Dockerfile, dockerfiles/centos/is-as-km/Dockerfile
- Modify Dockerfile to avoid warning logs in centos apim and is-as-km images
- Avoid warning logs printed by FileSystemPreferences class
- Create Java prefs directory to avoid warning logs printed by FileSystemPreferences class in centos apim and is-as-km images
- Set JAVA_OPTS as an environment variable with values for java.util.prefs.systemRoot and java.util.prefs.userRoot
=> [2.6.x] Modify Dockerfile to Avoid Warning Logs in Centos apim and is-as-km Images

dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
This PR adds OpenJDK11U-jdk_x64_linux_hotspot_11.0.13_8.tar.gz to the Ubuntu base images for APIM and APIM Analytics.
=> Add OpenJDK11U to the Ubuntu base images of APIM and APIM Analytics 3.2.x

dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/alpine/apim/Dockerfile
> Change the docker base image to Alphine
=> Change the docker base image to Alphine

CHANGELOG.md, dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/alpine/apim/Dockerfile
$subjet
Related PR: https://github.com/wso2/docker-apim/pull/424
=> [2.6.x] Update release version and add changelog

dockerfiles/alpine/apim/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
=> [APIM] [2.6.x] Modify Docker images to use base OS image and build Temurin OpenJDK

dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile
=> [APIM Analytics] [3.2.x] Modify Docker images to use base OS image and build Temurin OpenJDK 

dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile
=> [APIM Analytics] [2.6.x] Modify Docker images to use base OS image and build Temurin OpenJDK 

dockerfiles/alpine/apim/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
=> [APIM] [3.1.x] Modify Docker images to use base OS image and build Temurin OpenJDK 

dockerfiles/alpine/apim/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
=> [APIM] [3.0.x] Modify Docker images to use base OS image and build Temurin OpenJDK 

dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile
=> [APIM Analytics] [3.1.x] Modify Docker images to use base OS image and build Temurin OpenJDK 

dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile
=> [APIM Analytics] [3.0.x] Modify Docker images to use base OS image and build Temurin OpenJDK

dockerfiles/alpine/apim/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
=> [APIM] [3.2.x] Modify Docker images to use base OS image and build Temurin OpenJDK 

dockerfiles/alpine/apim/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/jdk8/alpine/apim/Dockerfile, dockerfiles/jdk8/centos/apim/Dockerfile, dockerfiles/jdk8/ubuntu/apim/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
=> Modify Dockerfiles to use base OS image and build Temurin OpenJDK

.gitignore, CHANGELOG.md, README.md, dockerfiles/centos/apim/Dockerfile, dockerfiles/centos/apim/README.md, dockerfiles/ubuntu/apim/Dockerfile, dockerfiles/ubuntu/apim/README.md
To support APIM 4.1.0-beta in dockerfiles.
https://github.com/wso2/docker-apim/pull/453
https://github.com/wso2/docker-apim/pull/454
=> Add support for APIM 4.1.0-beta in Docker images

CHANGELOG.md, dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/alpine/apim/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
This PR adds a new command to the Dockerfile to update the os packages in the Ubuntu images.
=> [3.2.x] Update os packages in Ubuntu image

docker-compose/apim-is-as-km-with-analytics/README.md, docker-compose/apim-with-analytics/README.md, docker-compose/apim-with-mi/README.md
This PR updates the docker-compose readme files on the possibility of using public images and `arm64` supported images for M1  Macbooks
=> [4.1.x] Update Readmes with public image and arm64 support

dockerfiles/alpine/apim/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
> Upgrade JDK version in APIM 3.2.0 Docker images to Temurin OpenJDK 11.0.17+8
=> [APIM][3.2.0] Upgrade JDK version to 11.0.17+8

dockerfiles/centos/apim/README.md, dockerfiles/jdk11/centos/apim/README.md, dockerfiles/jdk11/ubuntu/apim/README.md, dockerfiles/ubuntu/apim/README.md
> Rancher users cannot use port 9443 run Docker images. This PR will add instruction about a workaround to avoid the issue.
=> Add instruction to run images in Rancher

dockerfiles/alpine/is-as-km/Dockerfile, dockerfiles/centos/is-as-km/Dockerfile, dockerfiles/ubuntu/is-as-km/Dockerfile
> Upgrade JDK minor version
> Upgrade JDK version to 11.0.18_10
=> Modify Docker images to use base OS image and build Temurin OpenJDK

dockerfiles/alpine/apim/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
This PR bumps Ubuntu version to 22.04 and Alpine version to 3.19.0 in APIM 3.2.0 docker images.
Fixes https://github.com/wso2/api-manager/issues/2394
=> [3.2.x] Bump Ubuntu version to 22.04 and Alpine version to 3.19.0

dockerfiles/alpine/apim/Dockerfile
This PR bumps Alpine version to 3.19.0 in APIM docker image.
Fixes https://github.com/wso2/api-manager/issues/2394
=> Bump Alpine version to 3.19.0 of APIM

dockerfiles/alpine/apim/Dockerfile, dockerfiles/jdk11/alpine/apim/Dockerfile
> Update the Alpine base image from version 3.17.2 to 3.19.2.
> Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/6745
> Update the Alpine base image to version 3.19.2 in the Dockerfiles for both JDK 17 and JDK 11.
=> [4.2.x]  Update Alpine base image

dockerfiles/rocky/apim-analytics/dashboard/Dockerfile, dockerfiles/rocky/apim-analytics/worker/Dockerfile, dockerfiles/rocky/apim/Dockerfile
Changes related to https://github.com/wso2/api-manager/issues/3078
=> Add lang install to docker files

dockerfiles/alpine/apim/Dockerfile, dockerfiles/jdk8/alpine/apim/Dockerfile
- Update the Alpine base image from version 3.15 to 3.19.2.
- Update the Alpine base image to version 3.19.2 in the Dockerfiles for both JDK 8 and JDK 11.
- Update the JDK 8 version to ensure compatibility with Alpine 3.19.2.
- Remove unnecessary dependency installations from the JDK 8 Dockerfile.
=> [4.0.x] Update Alpine Base Image

dockerfiles/alpine/apim-analytics/dashboard/Dockerfile, dockerfiles/alpine/apim-analytics/worker/Dockerfile, dockerfiles/alpine/apim/Dockerfile, dockerfiles/centos/apim-analytics/dashboard/Dockerfile, dockerfiles/centos/apim-analytics/worker/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/rocky/apim-analytics/dashboard/Dockerfile, dockerfiles/rocky/apim-analytics/worker/Dockerfile, dockerfiles/rocky/apim/Dockerfile, dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/apim-analytics/worker/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
- [Upgrade JDK version used to 11.0.25_9](https://github.com/wso2/docker-apim/commit/a60c5b4187137e38c495fb591fb5f136c6e7b455)
- [Upgrade Ubuntu version to 24.04](https://github.com/wso2/docker-apim/commit/bf26f58a7ab05f79460525884b070e3fe2969b17)
=> [3.2.x] Upgrade JDK version to 11.0.25_9

dockerfiles/jdk11/alpine/apim/Dockerfile, dockerfiles/jdk11/centos/apim/Dockerfile, dockerfiles/jdk11/ubuntu/apim/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
- [Upgrade JDK version used to 11.0.25_9](https://github.com/wso2/docker-apim/pull/528/commits/c256bbbd91ee436747d7aa55c569cca351cd1c39)
- [Upgrade Ubuntu version to 24.04](https://github.com/wso2/docker-apim/pull/528/commits/3f2ccc0404a64b657633ee57f9d608c497853ba6)
=> [3.2.1.x] Upgrade JDK version to 11.0.25_9

dockerfiles/alpine/apim/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/jdk8/ubuntu/apim/Dockerfile, dockerfiles/rocky/apim/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
- [Upgrade JDK version to 11.0.25_9](https://github.com/wso2/docker-apim/commit/3188941e431efc2dc7aeb877e6f61131b61733b6)
- [Upgrade Ubuntu version to 24.04](https://github.com/wso2/docker-apim/commit/6e4b4ef76265656d1353351398fb19eea35073f2)
=> [4.0.x] Upgrade JDK version to 11.0.25_9

dockerfiles/alpine/apim/Dockerfile, dockerfiles/centos/apim/Dockerfile, dockerfiles/jdk8/ubuntu/apim/Dockerfile, dockerfiles/rocky/apim/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
- [Upgrade JDK version to 11.0.25_9](https://github.com/wso2/docker-apim/commit/bf8f9e7d819f9c311bc85057c34c571749e2629e)
- [Upgrade Ubuntu version to 24.04](https://github.com/wso2/docker-apim/commit/ff83490b08db77677e225f03add2e64e4e55eb2d)
=> [4.1.x] Upgrade JDK version to 11.0.25_9

dockerfiles/jdk11/alpine/apim/Dockerfile, dockerfiles/jdk11/centos/apim/Dockerfile, dockerfiles/jdk11/rocky/apim/Dockerfile, dockerfiles/jdk11/ubuntu/apim/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
- [Upgrade JDK version to 11.0.25_9](https://github.com/wso2/docker-apim/commit/67d6c5960ce99428802f50d231dd1e38a730e50e)
- [Upgrade Ubuntu version to 24.04](https://github.com/wso2/docker-apim/commit/391f0efcc78fd9fc8dbdc027bab8627a7c9d1297)
=> [4.2.x] Upgrade JDK version to 11.0.25_9

dockerfiles/jdk17/ubuntu/apim/Dockerfile, dockerfiles/ubuntu/apim/Dockerfile
This PR upgrades the Ubuntu version to 24.04.
=> [4.4.x] Upgrade Ubuntu version to 24.04

dockerfiles/alpine/apim/Dockerfile
This PR upgrades the alpine linux JDK 11 version to jdk-11.0.25+9.
=> [4.1.x] Upgrade the alpine linux JDK 11 version to jdk-11.0.25+9

dockerfiles/alpine/apim-tm/Dockerfile
This pull request will fix a bug in the Alpine image build process. The change removes the copying of the `synapse-configs` directory to the temporary directory during the Docker image build process.
* [`dockerfiles/alpine/apim-tm/Dockerfile`](diffhunk://#diff-2e45e6eaf44886b21b4b581d5d5d40fcd7ea1f4936b5b73b3a94169060088d76L104): Removed the line that copies the `synapse-configs` directory to the `wso2-tmp` directory.
=> Remove unnecessary copy of synapse-configs in Dockerfile

docker-compose/apim-is-as-km-with-analytics/docker-compose.yml
This pull request includes updates to the health check commands in the `docker-compose.yml` file for the `apim-is-as-km-with-analytics` service. The most important changes include modifying the health check tests for the `mysql` and `is-as-km` services.
Health check updates:
* [`docker-compose/apim-is-as-km-with-analytics/docker-compose.yml`](diffhunk://#diff-ce3ef27148da677ff609d287bf1a364fc4c2565ea08148046abf0a0d430897e7L32-R40): Updated the `mysql` service health check to ensure the initialization is complete by checking for a specific flag file.
* [`docker-compose/apim-is-as-km-with-analytics/docker-compose.yml`](diffhunk://#diff-ce3ef27148da677ff609d287bf1a364fc4c2565ea08148046abf0a0d430897e7L32-R40): Changed the `is-as-km` service health check to use a curl command to check the …
=> Update healthcheck commands in Docker Compose for improved reliability

dockerfiles/alpine/apim-tm/Dockerfile
This pull request includes a change to the `dockerfiles/alpine/apim-tm/Dockerfile` file. The change updates the user group configuration.
* [`dockerfiles/alpine/apim-tm/Dockerfile`](diffhunk://#diff-2e45e6eaf44886b21b4b581d5d5d40fcd7ea1f4936b5b73b3a94169060088d76L68-R68): Changed the `USER_GROUP` argument from `wso2` to `wso2-tm` for user/group configurations.
=> Update user group argument in Dockerfile for APIM TM

dockerfiles/alpine/apim-universal-gw/docker-entrypoint.sh, dockerfiles/rocky/apim-universal-gw/docker-entrypoint.sh, dockerfiles/ubuntu/apim-universal-gw/docker-entrypoint.sh
This pull request includes changes to the `docker-entrypoint.sh` script files for three different Docker environments to update the command used to start the WSO2 Carbon server.
Changes to start WSO2 Carbon server:
* [`dockerfiles/alpine/apim-universal-gw/docker-entrypoint.sh`](diffhunk://#diff-00195cd6c552920f43d9214eedd6db4dd688e79dd78af84527cbb5f184992469L59-R59): Updated the command from `api-gateway.sh` to `gateway.sh` to start the WSO2 Carbon server.
* [`dockerfiles/rocky/apim-universal-gw/docker-entrypoint.sh`](diffhunk://#diff-00195cd6c552920f43d9214eedd6db4dd688e79dd78af84527cbb5f184992469L59-R59): Updated the command from `api-gateway.sh` to `gateway.sh` to start the WSO2 Carbon server.
* [`dockerfiles/ubuntu/apim-universal-gw/docker-entrypoint.sh`](diffhunk://#diff-00195cd6c5529 …
=> Update entrypoint scripts to use gateway.sh instead of api-gateway.sh

docker-compose/apim-is-as-km-with-analytics/README.md, docker-compose/apim-is-as-km-with-analytics/conf/apim/repository/conf/deployment.toml, docker-compose/apim-is-as-km-with-analytics/docker-compose.yml, docker-compose/apim-with-analytics/README.md, docker-compose/apim-with-analytics/conf/apim/repository/conf/deployment.toml
- Fix the Health endpoint issue in Docker Compose.  
- If the user does not specify `apim.analytics.auth-token`, startup will fail due to an XML issue.  
- Docker Compose files should work with default values without requiring any additional configuration.  
- Update the Health endpoint.  
- Remove `<>` from the `deployment.toml` file.
=> Fix: Health endpoint issue in Docker compose

.github/workflows/docker-publish.yml
This pull request makes a minor update to the default Docker image tag in the GitHub Actions workflow configuration.
* Changed the default value of the `tag` input in `.github/workflows/docker-publish.yml` from `'latest'` to `'wso2/wso2am:latest'`, ensuring published images are tagged with the full repository and image name by default.
=> Change default Docker image tag in workflow
