- .gitignore
- docker-compose/pattern-1/docker-compose.yml
- docker-compose/pattern-2/README.md
- docker-compose/pattern-2/docker-compose.yml
Removed nginx in pattern-2. Tested for both compose and swarm.
> Pattern-1 and Pattern-2 converted 

- docker-compose/pattern-0/api-manager/carbon/repository/conf/carbon.xml
- docker-compose/pattern-1/api-manager/carbon/repository/conf/carbon.xml
- docker-compose/pattern-2/api-manager/carbon/repository/conf/carbon.xml
- docker-compose/pattern-3/docker-compose.yml
- docker-compose/pattern-3/gateway-manager/carbon/repository/conf/carbon.xml
- docker-compose/pattern-3/gateway-worker/carbon/repository/conf/carbon.xml
- docker-compose/pattern-3/publisher/carbon/repository/conf/carbon.xml
- docker-compose/pattern-3/store/carbon/repository/conf/carbon.xml
- docker-compose/pattern-4/docker-compose.yml
- docker-compose/pattern-4/gateway-manager-2/carbon/repository/conf/carbon.xml
- docker-compose/pattern-4/gateway-manager/carbon/repository/conf/carbon.xml
- docker-compose/pattern-4/gateway-worker-2/carbon/repository/conf/carbon.xml
- docker-compose/pattern-4/gateway-worker/carbon/repository/conf/carbon.xml
- docker-compose/pattern-4/publisher/carbon/repository/conf/carbon.xml
- docker-compose/pattern-4/store/carbon/repository/conf/carbon.xml
- docker-compose/pattern-5/docker-compose.yml
- docker-compose/pattern-5/gateway-manager/carbon/repository/conf/carbon.xml
- docker-compose/pattern-5/gateway-worker-km/carbon/repository/conf/carbon.xml
- docker-compose/pattern-5/publisher/carbon/repository/conf/carbon.xml
- docker-compose/pattern-5/store/carbon/repository/conf/carbon.xml
- docker-compose/pattern-6/docker-compose.yml
- docker-compose/pattern-6/gateway-manager/carbon/repository/conf/carbon.xml
- docker-compose/pattern-6/gateway-worker/carbon/repository/conf/carbon.xml
- docker-compose/pattern-6/publisher-store/carbon/repository/conf/carbon.xml
- docker-compose/pattern-7/api-manager/carbon/repository/conf/carbon.xml
> Revert "Removed svn based synchronization configurations."

- docker-compose/pattern-0/api-manager/carbon/repository/conf/carbon.xml
- docker-compose/pattern-1/api-manager/carbon/repository/conf/carbon.xml
- docker-compose/pattern-2/api-manager/carbon/repository/conf/carbon.xml
- docker-compose/pattern-3/docker-compose.yml
- docker-compose/pattern-3/gateway-manager/carbon/repository/conf/carbon.xml
- docker-compose/pattern-3/gateway-worker/carbon/repository/conf/carbon.xml
- docker-compose/pattern-3/publisher/carbon/repository/conf/carbon.xml
- docker-compose/pattern-3/store/carbon/repository/conf/carbon.xml
- docker-compose/pattern-4/docker-compose.yml
- docker-compose/pattern-4/gateway-manager-2/carbon/repository/conf/carbon.xml
- docker-compose/pattern-4/gateway-manager/carbon/repository/conf/carbon.xml
- docker-compose/pattern-4/gateway-worker-2/carbon/repository/conf/carbon.xml
- docker-compose/pattern-4/gateway-worker/carbon/repository/conf/carbon.xml
- docker-compose/pattern-4/publisher/carbon/repository/conf/carbon.xml
- docker-compose/pattern-4/store/carbon/repository/conf/carbon.xml
- docker-compose/pattern-5/docker-compose.yml
- docker-compose/pattern-5/gateway-manager/carbon/repository/conf/carbon.xml
- docker-compose/pattern-5/gateway-worker-km/carbon/repository/conf/carbon.xml
- docker-compose/pattern-5/publisher/carbon/repository/conf/carbon.xml
- docker-compose/pattern-5/store/carbon/repository/conf/carbon.xml
- docker-compose/pattern-6/docker-compose.yml
- docker-compose/pattern-6/gateway-manager/carbon/repository/conf/carbon.xml
- docker-compose/pattern-6/gateway-worker/carbon/repository/conf/carbon.xml
- docker-compose/pattern-6/publisher-store/carbon/repository/conf/carbon.xml
- docker-compose/pattern-7/api-manager/carbon/repository/conf/carbon.xml
> Revert "Revert "Removed svn based synchronization configurations.""

- dockerfiles/apim-analytics/Dockerfile
- dockerfiles/apim-analytics/README.md
- dockerfiles/apim/Dockerfile
- dockerfiles/apim/README.md
- dockerfiles/is-as-km/Dockerfile
- dockerfiles/is-as-km/README.md
Reduce the docker image size by copying the extracted distributions and update the readme files.
> Reduce image size for API-M Analytics and IS-KM

- dockerfiles/apim-analytics/Dockerfile
- dockerfiles/apim-analytics/README.md
- dockerfiles/apim/Dockerfile
- dockerfiles/apim/README.md
- dockerfiles/is-as-km/Dockerfile
- dockerfiles/is-as-km/README.md
Fix path errors in Dockerfile.
> Fix errors in Dockerfile

- docker-compose/apim-analytics/docker-compose.yml
- docker-compose/apim-is-as-km/docker-compose.yml
> Private Docker registry domain is added
> add private docker registry domain

- docker-compose/apim-analytics/README.md
- docker-compose/apim-analytics/docker-compose.yml
- docker-compose/apim-is-as-km/README.md
- docker-compose/apim-is-as-km/docker-compose.yml
- dockerfiles/apim-analytics/Dockerfile
- dockerfiles/apim-analytics/README.md
- dockerfiles/apim/Dockerfile
- dockerfiles/apim/README.md
- dockerfiles/is-as-km/Dockerfile
- dockerfiles/is-as-km/README.md
> fixes #88 
>MySQL connector jar is added via the Dockerfile. Since Docker Docker image already contains the MySQL connector, mounting MySQL connector in Docker-compose is removed.
> Add MySQL connector via Dockerfile

- docker-compose/apim-analytics/apim/repository/conf/tomcat/catalina-server.xml
- docker-compose/apim-is-as-km/apim/repository/conf/tomcat/catalina-server.xml
> Removes proxyport

- docker-compose/APIM-ISasKM-with-Analytics/README.md
- docker-compose/APIM-ISasKM-with-Analytics/docker-compose.yml
- docker-compose/APIM-with-Analytics/README.md
- docker-compose/APIM-with-Analytics/docker-compose.yml
> Change Docker registry from "dockerhub.wso2.com" to "docker.wso2.com"
fixes #94
> Set docker.wso2.com registry domain

- docker-compose/APIM-ISasKM-with-Analytics/README.md
- docker-compose/APIM-with-Analytics/README.md
> Fix issues in the Readme
fixes #96
> Fix errors in Readme

- docker-compose/APIM-with-Analytics/README.md
- docker-compose/APIM-with-Analytics/docker-compose.yml
Update APIM-with-Analytics README and healthcheck retries
> Update APIM-with-Analytics README and healthcheck retries

- docker-compose/APIM-ISasKM-with-Analytics/docker-compose.yml
> Port conflict in APIM-ISasKM-with-Analytics\docker-compose.yml is resolved.
> Host port mapping is changed.
fixes #105
> Resolve port conflict

- docker-compose/APIM-ISasKM-with-Analytics/docker-compose.yml
- docker-compose/APIM-with-Analytics/docker-compose.yml
> Updating "depends on" conditions and "links"
> Fixes #111
> Adding "depends on" conditions and "links"

- docker-compose/APIM-with-Analytics/apim/bin/wso2server.sh
- docker-compose/APIM-with-Analytics/apim/repository/conf/carbon.xml
- docker-compose/APIM-with-Analytics/apim/repository/conf/log4j.properties
- docker-compose/APIM-with-Analytics/apim/repository/deployment/server/jaggeryapps/portal/configs/designer.json
- docker-compose/APIM-with-Analytics/docker-compose.yml
> Configure Log analyzer
> Add configuration files for Log Analyzer
> Change Hostname from "api-manager" to "localhost"
> Disable Host Verification (via wso2server.sh)
fixes #117
> Configure Log Analyzer

- docker-compose/APIM-Microgateway-with-Analytics/README.md
Remove tag attached to the deployment diagram
> Remove Tag

- docker-compose/APIM-Microgateway-with-Analytics/README.md
> Revert "Remove Tag"

- .gitignore
> The `dockerfiles/apim/files` and  `dockerfiles/apim-analytics/files` folders are missing. These need to be added.
> Add files folder required for Docker image builds.
> Add files folder required for Docker image builds

- .gitignore
> Add end of the file line to .gitignore.
> Add end of the file line to .gitignore

- .gitignore
- README.md
> Push WSO2 API Manager maser Docker resources to 2.2.x - 04/07/2018.
> Merge master branch to 2.2.x

- docker-compose/apim-is-as-km-with-analytics/docker-compose.yml
- docker-compose/apim-with-analytics/docker-compose.yml
- dockerfiles/apim-analytics/init.sh
- dockerfiles/apim/init.sh
- dockerfiles/is-as-km/Dockerfile
- dockerfiles/is-as-km/init.sh
> Rename configuration mount folder in product containers from `volumes` to `wso2-server-volume`.
> Rename configuration mount folder in product containers with a meaningful name.
> Rename configuration mount folder in product containers

- dockerfiles/ubuntu/apim-analytics/README.md
- dockerfiles/ubuntu/apim/README.md
> Fix errors in README.md documentation.
> Fix errors in README.md documentation.
> Fix errors in README.md documentation

- docker-compose/apim-is-as-km-with-analytics/docker-compose.yml
- docker-compose/apim-with-analytics/docker-compose.yml
> Fix the order of startup of deployments involving APIM and APIM Analytics.
> Fix the order of startup of deployments involving APIM and APIM Analytics.
> Fix the order of startup of deployments involving APIM and APIM Analytics

- docker-compose/apim-is-as-km-with-analytics/docker-compose.yml
- docker-compose/apim-with-analytics/docker-compose.yml
- dockerfiles/ubuntu/apim-analytics/base/Dockerfile
- dockerfiles/ubuntu/apim-analytics/dashboard/docker-entrypoint.sh
- dockerfiles/ubuntu/apim-analytics/worker/docker-entrypoint.sh
- dockerfiles/ubuntu/apim/Dockerfile
- dockerfiles/ubuntu/apim/docker-entrypoint.sh
- dockerfiles/ubuntu/is-as-km/Dockerfile
- dockerfiles/ubuntu/is-as-km/docker-entrypoint.sh
> Fix issue with copying content from indirect volume mounts when multiple sub folders are present.
> Fix issue with copying content from indirect volume mounts when multiple sub folders are present
> Fix issue with copying content from indirect volume mounts when multiple sub folders are present

- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/alpine/apim/docker-entrypoint.sh
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/centos/apim/docker-entrypoint.sh
- dockerfiles/ubuntu/apim/Dockerfile
- dockerfiles/ubuntu/apim/docker-entrypoint.sh
> Add support for artifact synchronization between API Manager nodes. This fixes https://github.com/wso2/docker-apim/issues/230.
> Add support for artifact synchronization between API Manager nodes
> Support for artifact synchronization between API Manager nodes

- CHANGELOG.md
> Update release date for v2.6.0.6

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- dockerfiles/alpine/apim-analytics/dashboard/Dockerfile
- dockerfiles/alpine/apim-analytics/worker/Dockerfile
- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/alpine/apim/docker-entrypoint.sh
- dockerfiles/alpine/is-as-km/Dockerfile
- dockerfiles/centos/apim-analytics/dashboard/Dockerfile
- dockerfiles/centos/apim-analytics/worker/Dockerfile
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/centos/apim/docker-entrypoint.sh
- dockerfiles/centos/is-as-km/Dockerfile
- dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/apim-analytics/worker/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
- dockerfiles/ubuntu/apim/docker-entrypoint.sh
- dockerfiles/ubuntu/is-as-km/Dockerfile
> Merge 2.6.x branch with master branch - 2019-08-28.
> Merge 2.6.x branch with master branch
> Merge 2.6.x branch with master branch - 2019-08-28

- CHANGELOG.md
- README.md
> This PR updates the change log documentation. Plus, it adds the contributor guidelines to the repository.
> Update documentation
> Update change log documentation

- CHANGELOG.md
> Update the release date for `v2.6.0.8` in change log documentation.
> Update the release date for `v2.6.0.8`
> Update the release date for v2.6.0.8

- CHANGELOG.md
> Update the release date for `v3.0.0.2` in change log documentation.
> Update the release date for `v3.0.0.2`
> Update the release date for v3.0.0.2

- CHANGELOG.md
- README.md
- dockerfiles/alpine/apim-analytics/dashboard/README.md
- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/alpine/apim/docker-entrypoint.sh
- dockerfiles/centos/apim-analytics/dashboard/README.md
- dockerfiles/centos/apim/docker-entrypoint.sh
- dockerfiles/ubuntu/apim-analytics/dashboard/README.md
- dockerfiles/ubuntu/apim/docker-entrypoint.sh
> Merge 3.0.0 branch with master branch - 2019-11-05.
> Merge 3.0.0 branch with master branch
> Merge 3.0.0 branch with master branch - 2019-11-05

- dockerfiles/alpine/apim-analytics/dashboard/Dockerfile
- dockerfiles/alpine/apim-analytics/worker/Dockerfile
- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/alpine/is-as-km/Dockerfile
- dockerfiles/centos/apim-analytics/dashboard/Dockerfile
- dockerfiles/centos/apim-analytics/worker/Dockerfile
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/centos/is-as-km/Dockerfile
- dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/apim-analytics/worker/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
- dockerfiles/ubuntu/is-as-km/Dockerfile
Changed the MySQL jar download remote location.
Fixes #272
> Fix MySQL Download URL

- dockerfiles/alpine/apim-analytics/dashboard/Dockerfile
- dockerfiles/alpine/apim-analytics/worker/Dockerfile
- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/alpine/is-as-km/Dockerfile
- dockerfiles/centos/apim-analytics/dashboard/Dockerfile
- dockerfiles/centos/apim-analytics/worker/Dockerfile
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/centos/is-as-km/Dockerfile
- dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/apim-analytics/worker/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
- dockerfiles/ubuntu/is-as-km/Dockerfile
Change the remote location for downloading the MySQL connector jar.
>  fixes #272
> Fix MySQL connector jar Download URL

- CHANGELOG.md
>  Add changelog for release 3.0.0.2
fixes #276
> Add change log 

- CHANGELOG.md
- dockerfiles/alpine/apim-analytics/dashboard/Dockerfile
- dockerfiles/alpine/apim-analytics/worker/Dockerfile
- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/alpine/is-as-km/Dockerfile
- dockerfiles/centos/apim-analytics/dashboard/Dockerfile
- dockerfiles/centos/apim-analytics/worker/Dockerfile
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/centos/is-as-km/Dockerfile
- dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/apim-analytics/worker/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
- dockerfiles/ubuntu/is-as-km/Dockerfile
> Merge 3.0.x branch to master branch
> Merge 3.0.x branch to master branch

- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/alpine/apim/docker-entrypoint.sh
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/centos/apim/docker-entrypoint.sh
- dockerfiles/ubuntu/apim/Dockerfile
- dockerfiles/ubuntu/apim/docker-entrypoint.sh
> This PR adds support for WSO2 API Manager Solr indexing and fixes an issue with WSO2 API Manager profile optimization.
> Introduce WSO2 API Manager Docker image optimizations
> Introduce WSO2 API Manager Docker image optimizations

- CHANGELOG.md
- README.md
> Update change log documentation for release version 3.1.0.2.
> Update change log documentation
> Update change log documentation - release version 3.1.0.2

- CHANGELOG.md
- README.md
- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/alpine/apim/docker-entrypoint.sh
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/centos/apim/docker-entrypoint.sh
- dockerfiles/ubuntu/apim/Dockerfile
- dockerfiles/ubuntu/apim/docker-entrypoint.sh
> Merge 3.1.x branch to master branch - 2020-04-02
> Merge 3.1.x branch to master branch
> Merge 3.1.x branch to master branch

- docker-compose/pattern-7/is-key-manager/Dockerfile
In docker-compose for api manager pattern 7 and found that KM docker file is invalid.
https://github.com/wso2/docker-apim/blob/2.1.x/docker-compose/pattern-7/is-key-manager/Dockerfile
It should be corrected to use image docker.wso2.com/wso2is-km:5.3.0.
> Link(s) to product …
> Fixing is-km image type.

- dockerfiles/ubuntu/apim-analytics/README.md
- dockerfiles/ubuntu/apim-analytics/docker-entrypoint.sh
- dockerfiles/ubuntu/apim/Dockerfile
- dockerfiles/ubuntu/apim/README.md
- dockerfiles/ubuntu/is-as-km/Dockerfile
- dockerfiles/ubuntu/is-as-km/README.md
- dockerfiles/ubuntu/microgateway/README.md
Apply the older version of readme content with the change of how to build the docker image with new changes and Prerequisites.
> [2.2.0] Refactor Code

- CHANGELOG.md
- README.md
> This PR updates the change log documentation for the release `v3.2.0.1`.
> Update Change Log Documentation for Release `v3.2.0.1`
> [3.2.0] Update Change Log Documentation for Release v3.2.0.1

- dockerfiles/alpine/apim-analytics/dashboard/Dockerfile
- dockerfiles/alpine/apim-analytics/worker/Dockerfile
- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/centos/apim-analytics/dashboard/Dockerfile
- dockerfiles/centos/apim-analytics/worker/Dockerfile
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/apim-analytics/worker/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
> This PR fixes #338 #345 
> Add Docker release tag information as a label.
Enable SSL verification for `wget`
> [3.2.0] Add source label & add SSL verification for wget

- CHANGELOG.md
> [2.2.0] Update CHANGELOG for the latest release(2.2.0.6)

- CHANGELOG.md
> [2.5.0] Update CHANGELOG for the latest release(2.5.0.3)

- CHANGELOG.md
> [2.6.0] Update CHANGELOG for the latest release(2.6.0.9)

- CHANGELOG.md
> [3.0.0] Update CHANGELOG for the latest release(3.0.0.4)

- CHANGELOG.md
> [3.1.0] Update CHANGELOG for the latest release(3.1.0.3)

- CHANGELOG.md
> [3.2.0] Update CHANGELOG for the latest release(3.2.0.2)

- dockerfiles/alpine/apim-analytics/dashboard/Dockerfile
- dockerfiles/alpine/apim-analytics/worker/Dockerfile
- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/centos/apim-analytics/dashboard/Dockerfile
- dockerfiles/centos/apim-analytics/worker/Dockerfile
- dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/apim-analytics/worker/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
Update base image due to vulnerability in package freetype
> [3.2.x] Update base images

- CHANGELOG.md
- dockerfiles/centos/apim/Dockerfile
Address $subject and fixes https://github.com/wso2/docker-apim/issues/377
> [3.2.0.2] Update CHANGELOG for the latest release

- CHANGELOG.md
> Update change log date

- CHANGELOG.md
- dockerfiles/alpine/apim-analytics/dashboard/Dockerfile
- dockerfiles/alpine/apim-analytics/worker/Dockerfile
- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/centos/apim-analytics/dashboard/Dockerfile
- dockerfiles/centos/apim-analytics/worker/Dockerfile
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/apim-analytics/worker/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
Update master branch with the release changes of 3.2.0.2
> [3.2.0.2] Merge 3.2.x to master

- CHANGELOG.md
> [3.1.0] Update the release date
> Create a new release
> [3.1.0] Update the release date

- CHANGELOG.md
> [2.6.0] Update the release date
> Create a new release
> [2.6.0] Update the release date

- CHANGELOG.md
> [2.5.0] Update the release date
> Create a new release
> [2.5.x] Update the release date

- CHANGELOG.md
> [2.2.0] Update the release date
> Create a new release
> [2.2.x] Update the release date

- CHANGELOG.md
Update change log with the refering the issue
> [2.6.x] Update change log

- CHANGELOG.md
- README.md
> [3.1.x] Update change log

- CHANGELOG.md
- dockerfiles/alpine/apim-analytics/dashboard/Dockerfile
- dockerfiles/alpine/apim-analytics/worker/Dockerfile
- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/alpine/is-as-km/Dockerfile
- dockerfiles/centos/apim-analytics/dashboard/Dockerfile
- dockerfiles/centos/apim-analytics/worker/Dockerfile
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/centos/is-as-km/Dockerfile
- dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/apim-analytics/worker/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
- dockerfiles/ubuntu/is-as-km/Dockerfile
Fixes https://github.com/wso2/docker-apim/issues/394
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
> Upgrade MYSQL driver version in API-M 2.6 docker images

- dockerfiles/alpine/apim-analytics/dashboard/Dockerfile
- dockerfiles/alpine/apim-analytics/worker/Dockerfile
- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/centos/apim-analytics/dashboard/Dockerfile
- dockerfiles/centos/apim-analytics/worker/Dockerfile
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/apim-analytics/worker/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
This PR updates the base version of API-M 3.2.0 docker images
- **Ubuntu**: adoptopenjdk:11.0.10_9-jdk-hotspot-focal
- **Alpine**: adoptopenjdk/openjdk11:jdk-11.0.10_9-alpine
- **Centos**: adoptopenjdk/openjdk11:x86_64-centos-jdk-11.0.10_9
> Link(s) to product documentation that …
> Update base version of API-M 3.2.0 docker images

- dockerfiles/alpine/apim-analytics/dashboard/Dockerfile
- dockerfiles/alpine/apim-analytics/worker/Dockerfile
- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/alpine/is-as-km/Dockerfile
- dockerfiles/centos/apim-analytics/dashboard/Dockerfile
- dockerfiles/centos/apim-analytics/worker/Dockerfile
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/centos/is-as-km/Dockerfile
- dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/apim-analytics/worker/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
- dockerfiles/ubuntu/is-as-km/Dockerfile
Update base image of Alpine and Centos images. 
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
> Update base image of Alpine and Centos images

- docker-compose/apim-is-as-km-with-analytics/dockerfiles/apim/Dockerfile
- docker-compose/apim-is-as-km-with-analytics/dockerfiles/is-as-km/Dockerfile
- docker-compose/apim-with-analytics/dockerfiles/apim/Dockerfile
- docker-compose/apim-with-mi/dockerfiles/apim/Dockerfile
- docker-compose/apim-with-mi/dockerfiles/mi/Dockerfile
Update docker image tags for ones with U2.
> Update dockerfile image tags

- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
> Update base version of API-M 4.0.0 docker images

- CHANGELOG.md
> Update change log for 4.0.x

- docker-compose/apim-is-as-km-with-analytics/README.md
This PR updates the IS as KM doc url to point to the latest docs.
> Update IS as KM doc url

- CHANGELOG.md
- README.md
- dockerfiles/alpine/apim-analytics/dashboard/Dockerfile
- dockerfiles/alpine/apim-analytics/worker/Dockerfile
- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/alpine/is-as-km/Dockerfile
- dockerfiles/centos/apim-analytics/dashboard/Dockerfile
- dockerfiles/centos/apim-analytics/worker/Dockerfile
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/centos/is-as-km/Dockerfile
- dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/apim-analytics/worker/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
- dockerfiles/ubuntu/is-as-km/Dockerfile
Changed the base image versions in 2.6.0
> Changed the base image versions in 2.6.0

- .gitignore
- dockerfiles/ubuntu/is-as-km/Dockerfile
**Add Ubuntu 20.04 base image and add Adoptium OpenJDK8U-jdk_x64_linux_hotspot_8u312b07 to the base image  to reduce the issues introduced by the IS-KM 5.7.0 base image.** 
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus …
> Upgrade to ubuntu20.04 in IS-KM-5.7

- CHANGELOG.md
- dockerfiles/jdk8/alpine/apim/Dockerfile
- dockerfiles/jdk8/alpine/apim/README.md
- dockerfiles/jdk8/alpine/apim/docker-entrypoint.sh
- dockerfiles/jdk8/centos/apim/Dockerfile
- dockerfiles/jdk8/centos/apim/README.md
- dockerfiles/jdk8/centos/apim/docker-entrypoint.sh
- dockerfiles/jdk8/ubuntu/apim/Dockerfile
- dockerfiles/jdk8/ubuntu/apim/README.md
- dockerfiles/jdk8/ubuntu/apim/docker-entrypoint.sh
This PR adds support to build jdk8 images for APIM 4.0.0
Fixes https://github.com/wso2/product-apim/issues/12223
> Add support to build jdk8 images

- dockerfiles/centos/apim-analytics/dashboard/Dockerfile
- dockerfiles/centos/apim-analytics/worker/Dockerfile
- dockerfiles/ubuntu/apim-analytics/dashboard/Dockerfile
- dockerfiles/ubuntu/apim-analytics/worker/Dockerfile
> To create consistency in release tags in different OS options.
> [APIM Analytics][2.6.x] Change release tag

- dockerfiles/centos/apim/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
> To create consistency in release tags in different OS options.
> [APIM][2.6.x] Change release tag

- dockerfiles/alpine/apim/Dockerfile
> To create consistency in release tags in different OS options.
> [APIM][3.2.x] Change release tag

- CHANGELOG.md
> Update change log for 3.2.x

- CHANGELOG.md
> Update change log for 3.1.x 

- CHANGELOG.md
> Update change log for 3.0.x 

- CHANGELOG.md
> Update change log for 2.6.x

- CHANGELOG.md
> Update change log with v4.0.0.4

- CHANGELOG.md
> Update master change log with v4.0.0.4

- docker-compose/apim-is-as-km-with-analytics/conf/apim/repository/conf/deployment.toml
- docker-compose/apim-is-as-km-with-analytics/conf/is-as-km/repository/conf/deployment.toml
- docker-compose/apim-is-as-km-with-analytics/docker-compose.yml
This fixes an issue where the users cannot access the Admin portal in APIM and user portal in IS.
> Add config improvements to iskm docker-compose

- docker-compose/apim-with-mi/conf/apim/repository/conf/deployment.toml
> To support deployments without on-prem auth token
> Remove <on-prem-key> tag

- docker-compose/apim-is-as-km-with-analytics/README.md
- docker-compose/apim-with-analytics/README.md
- docker-compose/apim-with-mi/README.md
- dockerfiles/ubuntu/apim/README.md
Update Readmes with public image and arm64 support.
> Update Readmes with public image and arm64 support

- docker-compose/apim-is-as-km-with-analytics/conf/apim/repository/conf/deployment.toml
> Remove unnecessary spacing in IS as Key Manager deployment.toml file.
> Remove unnecessary spacing

- CHANGELOG.md
- dockerfiles/alpine/is-as-km/Dockerfile
- dockerfiles/centos/is-as-km/Dockerfile
- dockerfiles/ubuntu/is-as-km/Dockerfile
> Bump kubernetes membership schema to 1.0.11
> [ISKM-5.7.0] Bump kube membership schema version

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docker-compose/apim-is-as-km-with-analytics/README.md
- docker-compose/apim-is-as-km-with-analytics/dockerfiles/apim/Dockerfile
- docker-compose/apim-with-analytics/README.md
- docker-compose/apim-with-analytics/dockerfiles/apim/Dockerfile
- docker-compose/apim-with-mi/README.md
- docker-compose/apim-with-mi/dockerfiles/apim/Dockerfile
- docker-compose/apim-with-mi/dockerfiles/mi/Dockerfile
- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/alpine/apim/README.md
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/centos/apim/README.md
- dockerfiles/jdk11/alpine/apim/Dockerfile
- dockerfiles/jdk11/alpine/apim/README.md
- dockerfiles/jdk11/centos/apim/Dockerfile
- dockerfiles/jdk11/centos/apim/README.md
- dockerfiles/jdk11/ubuntu/apim/Dockerfile
- dockerfiles/jdk11/ubuntu/apim/README.md
- dockerfiles/ubuntu/apim/Dockerfile
- dockerfiles/ubuntu/apim/README.md
> Prepare Docker and Docker Compose artifacts for 4.2.0 release

- dockerfiles/alpine/apim/README.md
- dockerfiles/centos/apim/README.md
- dockerfiles/jdk11/alpine/apim/README.md
- dockerfiles/jdk11/centos/apim/README.md
- dockerfiles/jdk11/ubuntu/apim/README.md
- dockerfiles/ubuntu/apim/README.md
> Update instructions to build images

- dockerfiles/alpine/apim/README.md
- dockerfiles/centos/apim/README.md
- dockerfiles/jdk11/alpine/apim/README.md
- dockerfiles/jdk11/centos/apim/README.md
- dockerfiles/jdk11/ubuntu/apim/README.md
- dockerfiles/ubuntu/apim/README.md
> Update the compatible docker version

- dockerfiles/alpine/apim/README.md
- dockerfiles/centos/apim/README.md
- dockerfiles/jdk11/alpine/apim/README.md
- dockerfiles/jdk11/centos/apim/README.md
- dockerfiles/jdk11/ubuntu/apim/README.md
- dockerfiles/ubuntu/apim/README.md
> [4.2.x] Update the compatible docker version

- dockerfiles/alpine/apim/README.md
- dockerfiles/centos/apim/README.md
- dockerfiles/jdk11/alpine/apim/README.md
- dockerfiles/jdk11/centos/apim/README.md
- dockerfiles/jdk11/ubuntu/apim/README.md
- dockerfiles/ubuntu/apim/README.md
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
> Update the docker version

- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
> Update dockerfiles for APIM v4.3.0

- dockerfiles/alpine/apim/README.md
- dockerfiles/centos/apim/README.md
- dockerfiles/jdk11/alpine/apim/README.md
- dockerfiles/jdk11/centos/apim/README.md
- dockerfiles/jdk11/ubuntu/apim/README.md
- dockerfiles/rocky/apim/Dockerfile
- dockerfiles/rocky/apim/README.md
- dockerfiles/rocky/apim/docker-entrypoint.sh
> Add rocky linux based docker images for APIM

- dockerfiles/jdk11/rocky/apim/Dockerfile
- dockerfiles/jdk11/rocky/apim/README.md
- dockerfiles/jdk11/rocky/apim/docker-entrypoint.sh
> [4.2.x] Fix issues in Rocky Linux docker build

- dockerfiles/jdk8/rocky/apim/Dockerfile
- dockerfiles/jdk8/rocky/apim/README.md
- dockerfiles/jdk8/rocky/apim/docker-entrypoint.sh
> [4.0.x] Fix issues in Rocky Linux docker build

- dockerfiles/rocky/apim-analytics/dashboard/Dockerfile
- dockerfiles/rocky/apim-analytics/worker/Dockerfile
- dockerfiles/rocky/apim/Dockerfile
> [3.2.x] Fix issues in Rocky Linux docker build

- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
$subject
Related to https://github.com/wso2-enterprise/wso2-apim-internal/issues/6911 and https://github.com/wso2-enterprise/wso2-apim-internal/issues/6835
> Update JDK version in Dockerfiles to jdk8u372-b07

- dockerfiles/alpine/apim/Dockerfile
> [2.6.x] Fix checksum mismatch

- dockerfiles/rocky/is-as-km/Dockerfile
- dockerfiles/rocky/is-as-km/README.md
- dockerfiles/rocky/is-as-km/docker-entrypoint.sh
- Add rocky linux docker images
> [IS-KM 5.10] Add rocky linux for IS km 5.10

- dockerfiles/alpine/apim/Dockerfile
- dockerfiles/centos/apim/Dockerfile
- dockerfiles/jdk8/alpine/apim/Dockerfile
- dockerfiles/jdk8/centos/apim/Dockerfile
- dockerfiles/jdk8/rocky/apim/Dockerfile
- dockerfiles/jdk8/ubuntu/apim/Dockerfile
- dockerfiles/rocky/apim/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
> Upgrade rocky OS to 9.4

- .github/workflows/docker-publish.yml
> docker image pipeline

- dockerfiles/jdk21/ubuntu/apim/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
This PR upgrades the Ubuntu version to 24.04.
> [4.3.x] Upgrade Ubuntu version to 24.04

- dockerfiles/jdk17/ubuntu/apim/Dockerfile
- dockerfiles/ubuntu/apim/Dockerfile
This PR upgrades the Ubuntu version to 24.04.
> Upgrade Ubuntu version to 24.04

- CHANGELOG.md
- dockerfiles/alpine/is-as-km/Dockerfile
> [IS 5.10KM] Update Alpine based Docker Image Version to v3.20.3

- dockerfiles/alpine/apim/Dockerfile
> [4.0.x] Remove additional quotes

- .github/workflows/docker-publish.yml
This PR updates the plugin versions used in the docker publish workflow.
> Update docker plugins for the workflow
